import os
from dotenv import load_dotenv

load_dotenv()

CHROMA_DB_PATH = "./chroma_db"
CHROMA_DB_COLLECTION = "legal_documents"
LOCAL_DOCUMENT_DIRECTORY = "uploaded_pdfs"

AZURE_OPENAI_CM_API_KEY = os.getenv("AZURE_OPENAI_CM_API_KEY")
AZURE_OPENAI_CM_ENDPOINT = os.getenv("AZURE_OPENAI_CM_ENDPOINT") 
AZURE_OPENAI_CM_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_CM_DEPLOYMENT_NAME") 
AZURE_OPENAI_CM_API_VERSION = os.getenv("AZURE_OPENAI_CM_API_VERSION") 
MODEL_TEMPERATURE = 0

AZURE_OPENAI_EMB_MODEL_NAME= os.getenv("AZURE_OPENAI_EMB_MODEL_NAME")
AZURE_OPENAI_EMB_DEPLOYMENT_NAME= os.getenv("AZURE_OPENAI_EMB_DEPLOYMENT_NAME")
AZURE_OPENAI_EMB_ENDPOINT= os.getenv("AZURE_OPENAI_EMB_ENDPOINT")
AZURE_OPENAI_EMB_API_KEY= os.getenv("AZURE_OPENAI_EMB_API_KEY")
AZURE_OPENAI_EMB_API_VERSION= os.getenv("AZURE_OPENAI_EMB_API_VERSION")

BASE_LOG_PATH = "agent_logs"
SECURITY_LOG_PATH = os.path.join(BASE_LOG_PATH, "security_logs.jsonl")
